import os

def generate_gallery():
    image_dir = 'images'
    if not os.path.exists(image_dir):
        print(f"Directory {image_dir} does not exist.")
        return

    files = sorted(os.listdir(image_dir))

    html_content = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GEMINI LEGO Models Gallery</title>
    <style>
        body {
            background-color: #121212;
            color: #e0e0e0;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        h1 {
            color: #bb86fc;
            margin-bottom: 30px;
        }
        .gallery {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));
            gap: 25px;
            width: 100%;
            max-width: 1400px;
        }
        .card {
            background-color: #1e1e1e;
            border-radius: 12px;
            overflow: hidden;
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.5);
            transition: transform 0.3s ease;
        }
        .card:hover {
            transform: translateY(-5px);
        }
        .card img, .card video {
            width: 100%;
            height: auto;
            display: block;
        }
        .card-content {
            padding: 20px;
            background-color: #252525;
        }
        .card-title {
            font-size: 1.2rem;
            font-weight: 600;
            color: #03dac6;
        }
        footer {
            margin-top: 50px;
            color: #777;
            font-size: 0.9rem;
        }
    </style>
</head>
<body>
    <h1>GEMINI LEGO Models Gallery</h1>
    <div class="gallery">
"""

    models = {}
    for f in files:
        if f.endswith('.jpg') or f.endswith('.mp4'):
            name = os.path.splitext(f)[0]
            if name not in models:
                models[name] = {}
            if f.endswith('.jpg'):
                models[name]['image'] = f
            if f.endswith('.mp4'):
                models[name]['video'] = f

    for name in sorted(models.keys()):
        assets = models[name]
        html_content += f'        <div class="card">\n'
        if 'video' in assets:
            poster = f' poster="{image_dir}/{assets["image"]}"' if 'image' in assets else ''
            html_content += f'            <video autoplay loop muted playsinline{poster}>\n'
            html_content += f'                <source src="{image_dir}/{assets["video"]}" type="video/mp4">\n'
            html_content += f'            </video>\n'
        elif 'image' in assets:
            html_content += f'            <img src="{image_dir}/{assets["image"]}" alt="{name}">\n'

        html_content += f'            <div class="card-content">\n'
        html_content += f'                <div class="card-title">{name}</div>\n'
        html_content += f'            </div>\n'
        html_content += f'        </div>\n'

    html_content += """
    </div>
    <footer>
        <p>Generated by GEMINI Automation</p>
    </footer>
</body>
</html>
"""

    with open('index.html', 'w') as f:
        f.write(html_content)
    print("Gallery generated successfully in index.html")

if __name__ == "__main__":
    generate_gallery()
