import os

def generate_gallery():
    image_dir = 'images'
    models_dir = 'models'
    spec_file = 'specifications/sg13g2_stdcell_details.md'

    if not os.path.exists(models_dir):
        print(f"Directory {models_dir} does not exist.")
        return

    model_files = sorted([f for f in os.listdir(models_dir) if f.endswith('.ldr')])

    html_content = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GEMINI LEGO Models Gallery</title>
    <style>
        body {
            background-color: #121212;
            color: #e0e0e0;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        h1 {
            color: #bb86fc;
            margin-bottom: 30px;
        }
        .gallery {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));
            gap: 25px;
            width: 100%;
            max-width: 1400px;
        }
        .card {
            background-color: #1e1e1e;
            border-radius: 12px;
            overflow: hidden;
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.5);
            transition: transform 0.3s ease;
        }
        .card:hover {
            transform: translateY(-5px);
        }
        .card img, .card video {
            width: 100%;
            height: auto;
            display: block;
        }
        .card-content {
            padding: 20px;
            background-color: #252525;
        }
        .card-title {
            font-size: 1.2rem;
            font-weight: 600;
            color: #03dac6;
            margin-bottom: 10px;
        }
        .card-links {
            display: flex;
            gap: 15px;
            font-size: 0.9rem;
        }
        .card-links a {
            color: #bb86fc;
            text-decoration: none;
        }
        .card-links a:hover {
            text-decoration: underline;
        }
        footer {
            margin-top: 50px;
            color: #777;
            font-size: 0.9rem;
        }
    </style>
</head>
<body>
    <h1>GEMINI LEGO Models Gallery</h1>
    <div class="gallery">
"""

    for ldr_file in model_files:
        name = os.path.splitext(ldr_file)[0]
        jpg_file = f"{name}.jpg"
        mp4_file = f"{name}.mp4"

        has_jpg = os.path.exists(os.path.join(image_dir, jpg_file))
        has_mp4 = os.path.exists(os.path.join(image_dir, mp4_file))

        html_content += f'        <div class="card">\n'

        if has_mp4:
            poster = f' poster="{image_dir}/{jpg_file}"' if has_jpg else ''
            html_content += f'            <video autoplay loop muted playsinline{poster}>\n'
            html_content += f'                <source src="{image_dir}/{mp4_file}" type="video/mp4">\n'
            html_content += f'            </video>\n'
        elif has_jpg:
            html_content += f'            <img src="{image_dir}/{jpg_file}" alt="{name}">\n'
        else:
            html_content += f'            <div style="height: 200px; display: flex; align-items: center; justify-content: center; background: #333; color: #777;">Rendering pending...</div>\n'

        html_content += f'            <div class="card-content">\n'
        html_content += f'                <div class="card-title">{name}</div>\n'
        html_content += f'                <div class="card-links">\n'
        html_content += f'                    <a href="models/{ldr_file}" target="_blank">LDR</a>\n'
        if has_jpg:
            html_content += f'                    <a href="images/{jpg_file}" target="_blank">JPG</a>\n'
        if has_mp4:
            html_content += f'                    <a href="images/{mp4_file}" target="_blank">MP4</a>\n'
        html_content += f'                    <a href="{spec_file}#{name}" target="_blank">Spec</a>\n'
        html_content += f'                </div>\n'
        html_content += f'            </div>\n'
        html_content += f'        </div>\n'

    html_content += """
    </div>
    <footer>
        <p>Generated by GEMINI Automation</p>
    </footer>
</body>
</html>
"""

    with open('index.html', 'w') as f:
        f.write(html_content)
    print("Gallery generated successfully in index.html")

if __name__ == "__main__":
    generate_gallery()
